name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.61
authors:
  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  wakelock: ^0.2.0+1
  pedantic: ^1.8.0
  meta: ^1.2.3
  flutter_widget_from_html_core: ^0.5.0+5
  flutter_hls_parser: ^1.0.0
  visibility_detector: ^0.1.5
  path_provider: ^1.6.24
  flutter_portal: ^0.3.0
  marquee_text: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
 

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
 

  # To add assets to your application, add an assets section, like this:
  
flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: FLTBetterPlayerPlugin
 